sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: linux
    dist: trusty
    env: VERSION=5
  - os: osx
    osx_image: xcode8
    language: generic
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition bx
notifications:
  slack:
    secure: k02w4Ykndac2lunIV/orFHXKkDrUV0+0z3EvvyPXu9ctJ+sBMtI5+clmVivmhUuCxAdbAp3h59mpTTJCtTwQnvcE2hOJqTGxxtTHPPdp9+r4CzmdX+gMPRNYI1KqziKdG6h8Aa6lohWrnLSgmUtKVsbrzZl9BzDB2oMtPFNLMqUpcr91SoJ09BIeDLmGmeGKHuG2DMLcPPhyUcptnv1IFK5ELHVeV1ii4HD6u8H6GZ/bNj/ewtH/T89xKCzzpqzDXbRQgtdnv0zqYSkxpQh6dIcpuDDxWxxG0EudImGCQS37VgMh0ZmYgMBLahjL6o1vojEvk96bQIsEgusNRiZHtw1lDhpplROROi1S0YDruXSCYxL9uTEIsIimruOHAXwnye2o747ydSGdHkdGi+K2e4Arx0AMC3F1Pi4OpTXudsX8qD09g8RInOlEMbZmZ2xVt3jUecfHcvJlVhVDebXpdsNPcMeSJFW2cGw1p0G4mF1qkWoQCON7abHOlxchsrWXk72DAXPJFuuQqDRJ8Ou50+q92sjqbG3MtMybsO1qxn3aoOzVxIJ1kku/w9W68/Ew8OF1qN/B+BG07Ma7gloqhBAV2y7A3GPOj2ZiMB+jNdHgLhPfA/4ole5zmZdGoiDEkGQN8vDnYUWAf9qa60rX/8+A+vB5aQjNULBPy2JVSv4=
