sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic

install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
notifications:
    slack:
        secure: "CsxTq8teMOSfcz3LvoDTdGNhthGIArJ2vkI2qrB5juWsmR4hvZW9c2pOJWg7EziDhTAsKFLvm+w5F0jjkZk3bGb0Zrd4JBbnrcYmB5JoMS6bNF/y0nxT/PhifMNFvHmErWnspxfMzaeRwwcpMU0NEYDESotShyAaE11SXa7S8k36//Cic8qOiAsf8GQaG0x8h8gLNFUXFNM0c2KUBFLre28Yzy674by1Y8Y/i3DqPbqRyn/Htorej2pp4pjTd1eFePTYdm99iGVbR8jfQhc7y6CHxd+tymSS6xAn2flbC9b/PP5y6EoDjp56CrATffyw9HXn74Ylmy9IeYmeW361lRiD84Fs6Cd7g/ZlToXktexTSt0w74OvuT+BTcWNO4GaxbkMXZ1MNU6e0oe9AdRSk/CKOkXQJwT77kGkskkSx2+EOhUtL+z+kRqwkZGG25vxGYKHltCK11UdLc4hb4cJJL3vSD/PPd5qx6P9dVkncV0CbFf+PZh/yIu4BryqxCdOkri9JJPJLgsqTGzVq1NsMj0aJL3a/LpRs0rD+/9ulDjz7jHfW3Bso5HvBy+NVW5O4P/YybtgSXEUc9vt8BSHU6ss/se4v9Zh3JraXgfKLH6okmeI/4g6vs1gu5GQPiTxfzhCg7DRuT+VRdFyoJkPL2+x/GhGHCxMf5vn6UHvLag="